variables:
    IMAGE_NAME: flauw/learn_pipelines
    IMAGE_TAG: python_app.1.0

run_test:
    image: python:3.9-buster
    before_script:
        - apt-get update && apt-get install make
    script: 
        - make test

build_image:
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWD
    script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG learning_pipelines/build/Dockerfile
    - docker push $IMAGE_NAME:$IMAGE_TAG

